### ISSUE TITLE
Learn SlugSurvival API

### ISSUE THREAD

**Issue by kctoft** [tanmaymittal/cruzcal#10]
[SlugSurvival API](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwilw4iyho33AhVJpFsKHdxqDkIQFnoECAgQAQ&url=https%3A%2F%2Fslugsurvival.com%2Fexplain%2Fopensource&usg=AOvVaw3Dkm1sse-16cwZn0Z1gDUZ)

**Comment by pablofgaeta** [comment]
duplicate, removed from sprint 1
