### ISSUE TITLE
Frontend Design Mockup - Sprint 1

### ISSUE THREAD

**Issue by Aslimmax** [tanmaymittal/cruzcal#6]
Utilize Adobe XD/Figma to create a quick mockup of where each element will be positioned on the page

**Comment by Aslimmax** [comment]
Reference: https://antalmanac.com/

**Comment by tanmaymittal** [comment]
<img width="910" alt="Screen Shot 2022-04-11 at 9 17 01 AM" src="https://user-images.githubusercontent.com/43417880/162785136-6b70495e-39d9-4f5e-8dfe-3f56547a26b6.png">

**Comment by Aslimmax** [comment]
New mockup: https://www.figma.com/file/nP5Z4Ugc0p9pnBaqNrtMS4/CruzCal?node-id=0%3A1
