### ISSUE TITLE
Google Calendar Implementation

### ISSUE THREAD

**Issue by tanmaymittal** [tanmaymittal/cruzcal#79]
# Overview 
After signing in, the user selects a class. This class should be added to their calendar. 

# Goal 
Example: Enhance user experience by reducing animation delay. We want the animation to be as visible as possible. 
Given user Google OAuth token, add a calendar event for the selected class. 

# Requirements
- [x] Learn Google Calendar API
  - [x] Implement a function that takes in OAuth token and a calendar event json as argument. 
    - [x] Returns boolean about event completion 
- [x] Test
- [x] Documentation

**Comment by pablofgaeta** [comment]
Finished by Mario. Testing requirement has been added to a different issue
