### ISSUE TITLE
ics File Generation

### ISSUE THREAD

**Issue by tanmaymittal** [tanmaymittal/cruzcal#80]
# Overview 
When the user selects classes, they should be added to a schedule. The user then should be able to download this schedule as an .ics file. 

# Goal 
Enhance user experience by giving them the option to download their class schedule. 

# Requirements
- [x] Learn and explore ICS libraries
  - [x] Generate example events 
  - [x] Implement a function that takes in a calendar event json as argument
    - [x] Returns .ics file for the user to download
  - [x] Test
  - [x] Documentation

**Comment by pablofgaeta** [comment]
Backend implemented by Mario and frontend integration by Pablo
