### ISSUE TITLE
Endpoint for Google Calendar generation

### ISSUE THREAD

**Issue by Aslimmax** [tanmaymittal/cruzcal#87]
# Overview
When a user signs into Google, the classes they added are not syncing up with their Google Calendar.

# Goal 
Create an endpoint through Google using the Google Calendar API to sync the class schedule created on CruzCal onto Google Calendar.

# Requirements
- [x] Create an endpoint that syncs to Google's Calendar API

**Comment by pablofgaeta** [comment]
Finished by Pablo
