### ISSUE TITLE
Allow users to sign in with Google to associate a user with calendars

### ISSUE THREAD

**Issue by Aslimmax** [tanmaymittal/cruzcal#89]
# Overview
Users should be allowed to sign in with Google so that they can see their saved calendars

# Goal
Allows users to click on a sign in button to log them into Google

# Requirements
- [ ] Add a button to allow a user to login with Google
- [ ] Associate Users with Calendars in the table based on the Google Account

**Comment by pablofgaeta** [comment]
Implemented google authentication and can store their profile for calendar storage (still need to create tables and api to query and store calendars)
