### ISSUE TITLE
Notify user if adding a class has a time conflict (a modal/popup should appear that notifies the user about the time conflict, but still give them the option to add a class.)

### ISSUE THREAD

**Issue by Aslimmax** [tanmaymittal/cruzcal#95]
# Overview 
When a user attempts to add a class that has a time conflict, the user should be notified about the time conflict, but should still allow them to keep the overlapped class.

# Goal 
Display an alert or modal about the time conflict. Should display which classes have a time conflict

# Requirements
- [x] Design an alert/modal
- [x] Algorithm to do a linear search through the classes atom to determine if a time conflict exists

**Comment by kctoft** [comment]
Please see my recent PR,  Add warning for scheduling conflict #100
